spring:
  application:
    name: ThemeParkRide

server:
  port: 8080
  servlet:
    contextPath: /spring-boot

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
  #pattern:
    #console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    #file: "%d %p %c{1.} [%t] %m%n"
